export type {
  CreateStockMovementPayload,
  StockMovement,
  StockMovementProductInput,
  StockMovementType,
} from './domain/StockMovement'
export type { StockProduct } from './domain/StockProduct'
export type { StockOrderReference } from './domain/StockOrderReference'
export type { StockCompanyReference } from './domain/StockCompanyReference'
export type { StockProviderReference } from './domain/StockProviderReference'
export type { StockWineryReference } from './domain/StockWineryReference'
export type { IStockMovementRepository } from './domain/IStockMovementRepository'
export type { IProductCatalog } from './domain/IProductCatalog'
export type { IOrderReferenceLookup } from './domain/IOrderReferenceLookup'
export type { ICompanyLookup } from './domain/ICompanyLookup'
export type { IProviderLookup } from './domain/IProviderLookup'
export type { IWineryLookup } from './domain/IWineryLookup'
export { createStockMovement } from './application/createStockMovement'
export { createStockMovementForProduct } from './application/createStockMovementForProduct'
export { filterMovementsByProductQuery } from './application/filterMovementsByProductQuery'
export { formatOrderReferenceLabel } from './application/formatOrderReferenceLabel'
export { matchProductSearchQuery } from './application/matchProductSearchQuery'
export { getCompanyById } from './application/getCompanyById'
export { getOrderReferenceById } from './application/getOrderReferenceById'
export { getProductById } from './application/getProductById'
export { getProductCatalog } from './application/getProductCatalog'
export { getProviderById } from './application/getProviderById'
export { getWineryById } from './application/getWineryById'
export { mapOrderTypeToMovementType } from './application/mapOrderTypeToMovementType'
export { registerStockMovementsForOrder } from './application/registerStockMovementsForOrder'
export { resolveOrderReferences } from './application/resolveOrderReferences'
export { resolveProductIdsFromCodes } from './application/resolveProductIdsFromCodes'
export type {
  OrderLineForStockResolve,
  ProductCodeLookup,
} from './application/resolveProductIdsFromCodes'
export { companyLookup } from './infrastructure/AxiosCompanyLookup'
export { orderReferenceLookup } from './infrastructure/AxiosOrderReferenceLookup'
export { productCatalog } from './infrastructure/AxiosProductCatalog'
export { providerLookup } from './infrastructure/AxiosProviderLookup'
export { wineryLookup } from './infrastructure/AxiosWineryLookup'
export { stockMovementRepository } from './infrastructure/AxiosStockMovementRepository'
export { useStockMovementStore } from './presentation/stockMovementStore'
export { default as StockMovementsPage } from './presentation/StockMovementsPage.vue'
export { default as StockAssistantModal } from './assistant/presentation/organisms/StockAssistantModal.vue'
export { askStockAssistant } from './assistant/application/askStockAssistant'
export { ensureStockAssistantOllama } from './assistant/application/ensureStockAssistantOllama'
